/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as ProductosIndexRouteImport } from './../routes/productos/index'
import { Route as PedidosIndexRouteImport } from './../routes/pedidos/index'
import { Route as GastosIndexRouteImport } from './../routes/gastos/index'
import { Route as ClientesIndexRouteImport } from './../routes/clientes/index'
import { Route as BalanceIndexRouteImport } from './../routes/balance/index'
import { Route as ProductosNuevoRouteImport } from './../routes/productos/nuevo'
import { Route as ProductosIdRouteImport } from './../routes/productos/$id'
import { Route as PedidosNuevoRouteImport } from './../routes/pedidos/nuevo'
import { Route as PedidosIdRouteImport } from './../routes/pedidos/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosIndexRoute = GastosIndexRouteImport.update({
  id: '/gastos/',
  path: '/gastos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceIndexRoute = BalanceIndexRouteImport.update({
  id: '/balance/',
  path: '/balance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosNuevoRoute = ProductosNuevoRouteImport.update({
  id: '/productos/nuevo',
  path: '/productos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIdRoute = ProductosIdRouteImport.update({
  id: '/productos/$id',
  path: '/productos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosNuevoRoute = PedidosNuevoRouteImport.update({
  id: '/pedidos/nuevo',
  path: '/pedidos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/nuevo': typeof PedidosNuevoRoute
  '/productos/$id': typeof ProductosIdRoute
  '/productos/nuevo': typeof ProductosNuevoRoute
  '/balance/': typeof BalanceIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/gastos/': typeof GastosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/nuevo': typeof PedidosNuevoRoute
  '/productos/$id': typeof ProductosIdRoute
  '/productos/nuevo': typeof ProductosNuevoRoute
  '/balance': typeof BalanceIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/gastos': typeof GastosIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/productos': typeof ProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/nuevo': typeof PedidosNuevoRoute
  '/productos/$id': typeof ProductosIdRoute
  '/productos/nuevo': typeof ProductosNuevoRoute
  '/balance/': typeof BalanceIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/gastos/': typeof GastosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pedidos/$id'
    | '/pedidos/nuevo'
    | '/productos/$id'
    | '/productos/nuevo'
    | '/balance/'
    | '/clientes/'
    | '/gastos/'
    | '/pedidos/'
    | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pedidos/$id'
    | '/pedidos/nuevo'
    | '/productos/$id'
    | '/productos/nuevo'
    | '/balance'
    | '/clientes'
    | '/gastos'
    | '/pedidos'
    | '/productos'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pedidos/$id'
    | '/pedidos/nuevo'
    | '/productos/$id'
    | '/productos/nuevo'
    | '/balance/'
    | '/clientes/'
    | '/gastos/'
    | '/pedidos/'
    | '/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PedidosIdRoute: typeof PedidosIdRoute
  PedidosNuevoRoute: typeof PedidosNuevoRoute
  ProductosIdRoute: typeof ProductosIdRoute
  ProductosNuevoRoute: typeof ProductosNuevoRoute
  BalanceIndexRoute: typeof BalanceIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  GastosIndexRoute: typeof GastosIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos/': {
      id: '/gastos/'
      path: '/gastos'
      fullPath: '/gastos/'
      preLoaderRoute: typeof GastosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance/': {
      id: '/balance/'
      path: '/balance'
      fullPath: '/balance/'
      preLoaderRoute: typeof BalanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/nuevo': {
      id: '/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/productos/nuevo'
      preLoaderRoute: typeof ProductosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$id': {
      id: '/productos/$id'
      path: '/productos/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof ProductosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/nuevo': {
      id: '/pedidos/nuevo'
      path: '/pedidos/nuevo'
      fullPath: '/pedidos/nuevo'
      preLoaderRoute: typeof PedidosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PedidosIdRoute: PedidosIdRoute,
  PedidosNuevoRoute: PedidosNuevoRoute,
  ProductosIdRoute: ProductosIdRoute,
  ProductosNuevoRoute: ProductosNuevoRoute,
  BalanceIndexRoute: BalanceIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  GastosIndexRoute: GastosIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../../src/router.tsx'
import type { startInstance } from '../../src/ssr.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
